export type { Instance, RenderOptions, Root } from './root.js'
export { createRoot, renderSync } from './root.js'
export { default as render } from './root.js'
export { Box, Text } from './compat-components.js'
export type { BoxProps, TextProps } from './compat-components.js'
export { default as Newline } from './components/Newline.js'
export { default as Spacer } from './components/Spacer.js'
export { default as useApp } from './hooks/use-app.js'
export { default as useInput } from './hooks/use-input.js'
export { default as useStdin } from './hooks/use-stdin.js'
export { useSelection } from './hooks/use-selection.js'
export { useSearchHighlight } from './hooks/use-search-highlight.js'
export { default as measureElement } from './measure-element.js'
export { default as wrapText } from './wrap-text.js'
export { default as ScrollBox } from './components/ScrollBox.js'
export type { ScrollBoxHandle, ScrollBoxProps } from './components/ScrollBox.js'
export { AlternateScreen } from './components/AlternateScreen.js'
export { renderToString } from './testing.js'
export type { DOMElement } from './dom.js'
